version: "3"
services:
  db:
    image: "postgres:13-alpine"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - pre-agendamiento-network

  migrations:
    build: ./
    depends_on:
      - db
    networks:
      - pre-agendamiento-network
    command: -url=jdbc:postgresql://db:5432/postgres -user=admin -password=admin -connectRetries=60 migrate

  ms-pre-agendamiento:
    build: ./ms-pre-agendamiento/
    depends_on:
      - migrations
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__database: Server=db;Database=postgres;Port=5432;User Id=admin;Password=admin;Search Path=public;Ssl Mode=Disable;
    networks:
      - pre-agendamiento-network

networks:
  pre-agendamiento-network:
    
